### ISSUE TITLE
Need some help setting this up.

### ISSUE THREAD

**Issue by tleung999** [jhrv/sensu-influxdb-extension#6] opened 2015-10-20 06:51 UTC
Hi there,

I was wondering exactly which location did you put all the files.   I am running into a problem where I can see "{"timestamp":"2015-10-20T06:14:24.066092+0000","level":"info","message":"influxdb-extension: Successfully initialized config: hostname:"   But for some reason I look on my InfluxDB host and there is no data in the db I specified, I assume you can just list all the data by typing in "SHOW SERIES".    My Influx host is using the cloud hosted version from Influx.   The host has SSL enabled and is running 0.9.4.2

Here's the following location of my files.
/etc/sensu/extension/sensu-influxdb-extension.rb
/etc/sensu/conf.d/influxdb-extension.json
{
    "influxdb-extension": {
        "hostname": "myhostname",
        "port": "8086",
        "database": "sensu",
        "username": "myusername",
        "password": "mypassword"
    }
}

/etc/sensu/conf.d/handlers/metrics.json (I also tried putting the file in /etc/sensu/handlers/mertrics.json)
{
  "handlers": {
    "metrics": {
      "type": "set",
      "handlers": [ "influxdb-extension" ]
    }
  }
}

/etc/sensu/conf.d/checks/check_memory_metric.json
{
  "checks": {
    "memory_metric": {
      "type": "metric",
      "command": "/etc/sensu/plugins/check-memory-metrics.rb",
      "interval": 10,
      "handlers": [ "metrics" ],
      "subscribers": [
        "check_mem_metric"
      ]
    }
  }
}

I used this memory metric check
https://github.com/sensu/sensu-community-plugins/blob/master/plugins/system/memory-metrics.rb

I also see this in the log
{"timestamp":"2015-10-20T06:46:14.260104+0000","level":"info","message":"handler extension output","extension":{"type":"extension","name":"influxdb-extension"},"output":"influxdb-extension: Handler finished","status":0}

I'd appreciate any help.

Thanks!

**Comment by jhrv** [comment] 2015-10-20 07:14
Hi Tony. Can you run your sensu-server process with debug enabled, and let me know what the output is  from the extension?

**Comment by jhrv** [comment] 2015-10-20 07:40
I suspect the issue is related to you using SSL on InfluxDB. I've created a branch with support for this now here: https://github.com/jhrv/sensu-influxdb-extension/tree/develop

Can you check if this works for you? It should just be for you to update the extension and add "ssl: true" to your influxdb-extension json-config.

**Comment by jhrv** [comment] 2015-10-29 15:08
closing due to missing response

**Closed as completed by jhrv** 2015-10-29 15:08 UTC
